### PR TITLE
4 fort upgrades

### PR DESCRIPTION
**Pull request by Mxt-dot**
make AI upgrade forts when new fort-versions roll out ( mil tech 14, 19, 24) and upgrade capital with a proper fort.

### CODE REVIEW

**Comment by stackpoint** [comment]
Good job getting this working. AI build logic is pretty awful in this game.

I believe the "can_build = fort_Xth" condition covers any tech restrictions and if the building had already been constructed in the province. Keeps you from having the reference the tech level constantly.

**Comment by Mxt-dot** [comment]
Hey there, thanks for the tip!

I'll change it today/tomorrow, though overall this problem wasn't so difficult to solve. Most of the time the last few days I tried to get the ai_army script to work, but yeah, no documentation - no chance. 

Offtopic:
Next task will be the missionary conversions or making the AI actually build buildings even when seemingly low on money.

Perhaps I'll also reduce the mercenary spam by tying the available mercenaries to war enthusiasm/loans for the AI (or more concrete: the penalty of it). Gotta have a bit of thinking about it :)

**Comment by stackpoint** [comment]
It's good to hear you're still working on this. The first steps is writing down everything that's wrong with the AI. 👍

**Comment by Mxt-dot** [comment]
Of course, I won't stop this project and if people have further recommendations I'll try to implement them. The next few months personally will be a bit stressful, so no worries, I'm still on everything, could just be a bit delayed.

Just as an information for you and for anybody reading this

**Pull request merged**
