### PR TITLE
Condensing ManaEvents.txt logic (more commits)

### PR DESCRIPTION
**Pull request by stackpoint**
Condensed the logic for "doesnt have institution until 30 years after spawn outside of europe and has devable capital" with more modular commits.

This should be easier to see what I've done without all the changes being mashed together. I'm a GitHub novice so please bear with me.

### CODE REVIEW

**Comment by stackpoint** [comment]
> I know there are some funky cases where the AI tries to devpush capital, has the restriction that it can't do so due to dev > 20 so it doesn't develop the province, but still the root = {} triggers and deducts mana. This was fixed, but I can't judge by eye if this occurs in your version.

This could be a result of the logic not being nested in the if/else_if scopes. I'll try to reproduce this in this branch but I'm not sure how it could happen without seeing the original code.

**Comment by Mxt-dot** [comment]
Must have been the if/else scopes yeah, though if you have a province scope limit = { } somewhere which has 0 results, does this mean the whole block afterwards is ignored? I assumed it tried to apply everything afterwards on the returned "list", no matter if there's 0 results.

> This should be easier to see what I've done without all the changes being mashed together. I'm a GitHub novice so please bear with me.

This is also my first real github project, quite a bit different to stuff like gitlab. Especially the workflow... so no worries.

Sorry for postponing the review, but I'll check your newest patch on thursday, to be exact :) Can't find time before, sadly.

**Comment by stackpoint** [comment]
> Must have been the if/else scopes yeah, though if you have a province scope limit = { } somewhere which has 0 results, does this mean the whole block afterwards is ignored? I assumed it tried to apply everything afterwards on the returned "list", no matter if there's 0 results.

I don't know definitely, but it would be a bit strange for the code in the province scope to run if the limit didn't return a province.

> Sorry for postponing the review, but I'll check your newest patch on thursday, to be exact :) Can't find time before, sadly.

None of this affects the actual performance of the code; so if reviewing it and any follow up code on this would take a significant amount of time then it's probably not worth the effort to modify the code since it pretty much works as intended.

Your development time is definitely better spent working on something new than retreading this.

**Comment by Mxt-dot** [comment]
Continued on #5

**Pull request merged**
