### PR TITLE
Condensing ManaEvents.txt logic

### PR DESCRIPTION
**Pull request by stackpoint**
Condensed the logic for "doesnt have institution until 30 years after spawn outside of europe and has devable capital".

I can also do the rest of the event but want to see if you're interested first.

### CODE REVIEW

**Comment by Mxt-dot** [comment]
I didn't expect that much of help! :) 

Will look into it tomorrow more closely, though I changed some of the years for devpushing the institution/added a split in logic for the natives, so I'll edit the file later on. But it's looking way more manageable this way.

Also if you like, you can do the rest, though it's tedious work, so I can do it aswell heh.

**Comment by stackpoint** [comment]
If you have more you want to work on, then further work on this can definitely wait until then.

I am willing to do the rest but the decision is up to you. Your code is very well structured so it's not too much of an issue either way.

**Comment by Mxt-dot** [comment]
Currently I'm doing some testing for the AI script, and after that I want to do the logic for the fort upgrades. If you find some spare time to do the rest of it, feel free to do so :) 

Not sure if I'll be able to test your version already, but I would like to do this before accepting the pull request :) 
You know if I can get the full file download somehow already? (nvm, found out.. weird github)

I know there are some funky cases where the AI tries to devpush capital, has the restriction that it can't do so due to dev > 20 so it doesn't develop the province, but still the root = {} triggers and deducts mana. This was fixed, but I can't judge by eye if this occurs in your version.

**Comment by stackpoint** [comment]
I have broken this pull request into more individual commits here: https://github.com/Mxt-dot/BetterAI/pull/4

**Pull request closed without merging**
